export const SITE_NAME = 'James Bond Cleaning';
export const SITE_PHONE_NUMBER = '1300 123 456';
export const SITE_PHONE_HREF = 'tel:1300123456';
export const SITE_EMAIL = 'contact@jamesbondcleaning.com.au';
export const SITE_EMAIL_HREF = 'mailto:contact@jamesbondcleaning.com.au';

export const NAVIGATION_LINKS = [
  { name: 'Home', href: '/' },
  { name: 'About Us', href: '/about' },
  { name: 'Services', href: '/services' },
  { name: 'Suburbs', href: '/suburbs' },
  { name: 'Contact', href: '/contact' },
];

export const SERVICES = [
  {
    title: 'Bond Cleaning',
    description: 'Complete end-of-lease cleaning tailored to real estate requirements.',
    href: '/services#bond-cleaning',
    imagePlaceholder: 'bond-cleaning',
  },
  {
    title: 'Carpet Steam Cleaning',
    description: 'Deep steam cleaning to remove stains, dirt, and allergens from your carpets.',
    href: '/services#carpet-cleaning',
    imagePlaceholder: 'carpet-cleaning',
  },
  {
    title: 'Spring Cleaning',
    description: 'Comprehensive top-to-bottom cleaning to refresh your home.',
    href: '/services#spring-cleaning',
    imagePlaceholder: 'spring-cleaning',
  },
  {
    title: 'Deep Cleaning',
    description: 'Intensive cleaning to restore your property to a pristine condition.',
    href: '/services#deep-cleaning',
    imagePlaceholder: 'deep-cleaning',
  },
  {
    title: 'Pest Control',
    description: 'Professional pest management services to keep your home safe and bug-free.',
    href: '/services#pest-control',
    imagePlaceholder: 'pest-control',
  },
  {
    title: 'Builder Cleaning',
    description: 'Detailed post-construction cleaning to make your new space ready to move in.',
    href: '/services#builder-cleaning',
    imagePlaceholder: 'builder-cleaning',
  },
  {
    title: 'Upholstery Cleaning',
    description: 'Revitalize and protect your furniture with our expert upholstery cleaning.',
    href: '/services#upholstery-cleaning',
    imagePlaceholder: 'upholstery-cleaning',
  },
  {
    title: 'Removalist',
    description: 'Safe, reliable, and efficient moving services for a stress-free relocation.',
    href: '/services#removalist',
    imagePlaceholder: 'removalist',
  },
  {
    title: 'Painting',
    description: 'High-quality residential and commercial painting services to transform your space.',
    href: '/services#painting',
    imagePlaceholder: 'painting',
  },
  {
    title: 'Pressure Washing',
    description: 'Powerful exterior cleaning for driveways, pathways, and building facades.',
    href: '/services#pressure-washing',
    imagePlaceholder: 'pressure-washing',
  },
  {
    title: 'Pool Maintenance',
    description: 'Regular pool cleaning and balancing to keep your pool sparkling year-round.',
    href: '/services#pool-maintenance',
    imagePlaceholder: 'pool-maintenance',
  },
];

export const SERVICE_AREA_GOLD_COAST = [
  'Carrara',
  'Coombabah',
  'Coolangatta',
  'Elanora',
  'Pimpama',
  'Hope Island',
  'Helensvale',
  'Coomera',
  'Upper Coomera',
  'Southport',
  'Surfers Paradise',
  'Paradise Point',
  'Broadbeach',
  'Palm Beach',
  'Main Beach',
  'Pacific Pines',
  'Runaway Bay',
  'Parkwood',
  'Broadbeach Waters',
  'Bundall',
  'Arundel',
  'Burleigh Heads',
  'Burleigh Waters',
  'Currumbin',
  'Currumbin Waters',
  'Tugun',
  'Advancetown',
  'Bonogin',
  'Mudgeeraba',
  'Reedy Creek',
  'Robina',
  'Taigum',
  'Miami',
  'Mermaid Waters',
  'Nerang',
  'Ormeau',
  'Oxenford',
  'Springbrook',
  'Tweed Heads',
  'Varsity Lakes',
];

export const SERVICE_AREA_BRISBANE = [
  'Brisbane City',
  'Spring Hill',
  'Fortitude Valley',
  'Chermside',
  'Kedron',
  'Stafford',
  'Aspley',
  'Acacia Ridge',
  'Alberton',
  'Ashgrove',
  'Brendale',
  'Carseldine',
  'Coorparoo',
  'Clayfield',
  'Greenslopes',
  'Geebung',
  'Heathwood',
  'North Lakes',
  'Nundah',
  'Moorooka',
  'Mount Gravatt',
  'Richmond',
  'Springfield Lakes',
  'South Brisbane',
  'Woolloongabba',
  'Annerley',
  'East Brisbane',
  'Kangaroo Point',
  'Norman Park',
  'Morningside',
  'Toowong',
  'Indooroopilly',
  'St Lucia',
  'Kenmore',
  'Logan',
  'Ipswich',
  'Springfield',
  'Carindale',
  'Sunnybank',
  'Redcliffe',
  'Capalaba',
  'Wynnum',
  'Forest Lake',
];

export const OPENING_HOURS = {
  days: 'Monday - Saturday',
  hours: '8:00 AM - 6:00 PM',
};
