export const SITE_NAME = 'James Bond Cleaning';
export const SITE_PHONE_NUMBER = '1300 123 456';
export const SITE_PHONE_HREF = 'tel:1300123456';
export const SITE_EMAIL = 'contact@jamesbondcleaning.com.au';
export const SITE_EMAIL_HREF = 'mailto:contact@jamesbondcleaning.com.au';

export const NAVIGATION_LINKS = [
  { name: 'Home', href: '/' },
  { name: 'About Us', href: '/about' },
  { name: 'Services', href: '/services' },
  { name: 'Suburbs', href: '/suburbs' },
  { name: 'Contact', href: '/contact' },
];

export const SERVICES = [
  {
    title: 'Bond Cleaning',
    description:
      'Complete end-of-lease cleaning tailored to real estate requirements.',
    href: '/services#bond-cleaning',
    imagePlaceholder: 'bond-cleaning',
  },
  {
    title: 'Carpet Cleaning',
    description: 'Deep steam cleaning to remove stains, dirt, and allergens.',
    href: '/services#carpet-cleaning',
    imagePlaceholder: 'carpet-cleaning',
  },
  {
    title: 'Spring / Deep Cleaning',
    description:
      'Comprehensive top-to-bottom cleaning for homes and rental properties.',
    href: '/services#spring-cleaning',
    imagePlaceholder: 'spring-cleaning',
  },
];

export const SERVICE_AREA_GOLD_COAST = [
  'Carrara',
  'Coombabah',
  'Coolangatta',
  'Elanora',
  'Pimpama',
  'Hope Island',
  'Helensvale',
  'Coomera',
  'Upper Coomera',
  'Southport',
  'Surfers Paradise',
  'Paradise Point',
  'Broadbeach',
  'Palm Beach',
  'Main Beach',
  'Pacific Pines',
  'Runaway Bay',
  'Parkwood',
  'Broadbeach Waters',
  'Bundall',
  'Arundel',
  'Burleigh Heads',
  'Burleigh Waters',
  'Currumbin',
  'Currumbin Waters',
  'Tugun',
  'Advancetown',
  'Bonogin',
  'Mudgeeraba',
  'Reedy Creek',
  'Robina',
  'Taigum',
  'Miami',
  'Mermaid Waters',
  'Nerang',
  'Ormeau',
  'Oxenford',
  'Springbrook',
  'Tweed Heads',
  'Varsity Lakes',
];

export const SERVICE_AREA_BRISBANE = [
  'Brisbane City',
  'Spring Hill',
  'Fortitude Valley',
  'Chermside',
  'Kedron',
  'Stafford',
  'Aspley',
  'Acacia Ridge',
  'Alberton',
  'Ashgrove',
  'Brendale',
  'Carseldine',
  'Coorparoo',
  'Clayfield',
  'Greenslopes',
  'Geebung',
  'Heathwood',
  'North Lakes',
  'Nundah',
  'Moorooka',
  'Mount Gravatt',
  'Richmond',
  'Springfield Lakes',
  'South Brisbane',
  'Woolloongabba',
  'Annerley',
  'East Brisbane',
  'Kangaroo Point',
  'Norman Park',
  'Morningside',
  'Toowong',
  'Indooroopilly',
  'St Lucia',
  'Kenmore',
  'Logan',
  'Ipswich',
  'Springfield',
  'Carindale',
  'Sunnybank',
  'Redcliffe',
  'Capalaba',
  'Wynnum',
  'Forest Lake',
];

export const OPENING_HOURS = {
  days: 'Monday - Saturday',
  hours: '8:00 AM - 6:00 PM',
};
